version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_DB_URI=mongodb+srv://adityamishra34351729:WxOV8TmcsqA8e7DL@dollarsignonetime.9gpeigl.mongodb.net/chat-app-db?retryWrites=true&w=majority&appName=DollarSignOneTime
      - JWT_SECRET=WB9gclK9xq8NAARgJU56PC70FTas7uH+oeQ5VcY7t+Y=
      - NODE_ENV=development
      - PORT2=3000
    volumes:
      - ./backend:/app/backend
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT2=3000
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    depends_on:
      - backend